### ISSUE TITLE
[v5] `@todo` items in codes

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#6808]
### Todo List in v5

- [ ] Add return type declaration
Basti: *Those are unfortunately all for the `collection()` feature and I know that some users "abuse" this to not just return Collections. If we add return types here, we would break that. Not sure if it's worth it and if we gain much from the return type.* 
Nico: move at least to v6
https://github.com/getkirby/kirby/blob/d2eb35fbb2d50e8c7b0be994f7e6a4e37ee01ff5/config/helpers.php#L56
https://github.com/getkirby/kirby/blob/2acb9a1b30f5e420d9fd424ecbab2e41e67dcfb9/src/Cms/App.php#L378
https://github.com/getkirby/kirby/blob/af1da17cb5affbc7f995d33024d0b5fef29abac0/src/Cms/Collections.php#L44
- [ ] Add deprecation warning when anything else than a Collection is returned
Basti: *see above*
Nico: move at least to v6
https://github.com/getkirby/kirby/blob/af1da17cb5affbc7f995d33024d0b5fef29abac0/src/Cms/Collections.php#L55
- [ ] remove this check when `read` option deprecated in v5
Nico: postpone and base on what permissions changes in the working require after all
https://github.com/getkirby/kirby/blob/464c09ea2b308d1986e0cd7ff98e02b7e0851b55/src/Cms/File.php#L316
https://github.com/getkirby/kirby/blob/464c09ea2b308d1986e0cd7ff98e02b7e0851b55/src/Cms/File.php#L335
https://github.com/getkirby/kirby/blob/464c09ea2b308d1986e0cd7ff98e02b7e0851b55/src/Cms/File.php#L356
https://github.com/getkirby/kirby/blob/05d31fa3502d71c7a265a841638505017edb6d92/src/Cms/Page.php#L520
https://github.com/getkirby/kirby/blob/05d31fa3502d71c7a265a841638505017edb6d92/src/Cms/Page.php#L682
https://github.com/getkirby/kirby/blob/05d31fa3502d71c7a265a841638505017edb6d92/src/Cms/Page.php#L746
- [ ] Remove `acceptMime` method
https://github.com/getkirby/kirby/blob/f850de8bc351a9cd3892e7c749052efbfc335a73/src/Cms/FileBlueprint.php#L63
- [ ] Consider more descriptive name and maybe move to a different class
https://github.com/getkirby/kirby/blob/fa87fc87fc0760a6e47508698ed1ab22aa4c31c9/src/Content/Storage.php#L33
- [ ] use actual in-memory page in v5
Nico: move at least to v6
https://github.com/getkirby/kirby/blob/af1da17cb5affbc7f995d33024d0b5fef29abac0/src/Panel/PageCreateDialog.php#L259
- [ ] Check if case-sensitive can become the default mode, see https://github.com/getkirby/kirby/pull/5635
https://github.com/getkirby/kirby/blob/af1da17cb5affbc7f995d33024d0b5fef29abac0/src/Toolkit/Collection.php#L34

**Comment by afbora** [comment]
Feel free to add, edit, update, delete or assign yourself for the tasks.

**Comment by distantnative** [comment]
@afbora Thanks for collecting these!

I think we should re-evaluate each of them. Just because we added the to-do during v4 to have the breaking change in v5 doesn't mean we must do it. There might be cases where it would be better to wait for another major version (v6) with not much downside, but to spare developers of another breaking change.

But that's probably a case by case decision.

**Comment by afbora** [comment]
I totally agree. The reason I created the issue is so that we don't miss it.

**Comment by bastianallgeier** [comment]
I've started adding inline comments. Not the ideal format, but I think it's readable enough :)

**Comment by afbora** [comment]
@bastianallgeier We can move the issue into Notion if you want. The discussion will proceed better in there.

**Comment by johannschopplich** [comment]
I have a wish for the todo list:
- Remove deprecated [legacy Panel aliases](https://github.com/getkirby/kirby/blob/v5/develop/panel/src/panel/legacy.js). I think it would make sense for v5 to clean up the aliases and prefer, e.g. `this.$panel.t` over `this.$panel.$t`. 
- The `window.panel.$vue` alias for kirbyup can be removed as well, since kirbyup uses `window.panel.app` since the last major version.

**Comment by jirichlebus** [comment]
I have one wish for 5.0.0-beta.2 update:

Panel view buttons should be able to translate **text field** to another languages, for example:

```
buttons:
  - preview
  - languages
  analytics:
    icon: chart
    text:
      cs: Analytika
      en: Analytics
    link: https://my-analytics.com/for/this/page
    theme: aqua-icon
```
